Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -9,25 +9,29 @@ jobs:
   build:
     runs-on: ubuntu-latest
 
-    steps:        
-      - name: Deploy to EC2
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.EC2_HOST }}
-          username: ${{ secrets.EC2_USER }}
-          key: ${{ secrets.EC2_KEY }}
-          script: | 
-            cd /home/ubuntu/hello-world-app
-            # Install pm2 if not already installed
-            if ! command -v pm2 &> /dev/null
-            then
-              echo "pm2 not found, installing..."
-              sudo npm install -g pm2
-            else
-              echo "pm2 is already installed"
-            fi
-            git pull origin main
-            npm install
-            npm run build
-            pm2 start npm --name hello-world-app
-            EOF
+    steps:
+    - name: Checkout Code
+      uses: actions/checkout@v2
+
+            
+    - name: Deploy to EC2
+      uses: appleboy/ssh-action@master
+      with:
+        host: ${{ secrets.EC2_HOST }}
+        username: ${{ secrets.EC2_USER }}
+        key: ${{ secrets.EC2_KEY }}
+        script: | 
+          cd /home/ubuntu/hello-world-app
+          # Install pm2 if not already installed
+          if ! command -v pm2 &> /dev/null
+          then
+            echo "pm2 not found, installing..."
+            sudo npm install -g pm2
+          else
+           echo "pm2 is already installed"
+          fi
+          git pull origin main
+          npm install
+          npm run build
+          pm2 start npm --name hello-world-app
+          EOF
